-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."discord_guilds" add column "scoreboard_channel_id" text
--  null;
