-- Create match_clips table for storing Allstar clips
CREATE TABLE IF NOT EXISTS "public"."match_clips" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "match_id" UUID NOT NULL,
  "match_map_id" UUID NOT NULL,

  -- Allstar identifiers
  "allstar_clip_id" TEXT,
  "allstar_request_id" TEXT,

  -- Clip URLs
  "clip_url" TEXT,
  "thumbnail_url" TEXT,
  "snapshot_url" TEXT,

  -- Clip metadata
  "clip_type" TEXT NOT NULL DEFAULT 'potg', -- potg, bp, pmh
  "status" TEXT NOT NULL DEFAULT 'pending', -- pending, processing, processed, error
  "error_message" TEXT,

  -- Player info (for player-specific clips)
  "steam_id" TEXT,
  "player_name" TEXT,

  -- Clip details from Allstar
  "clip_title" TEXT,
  "clip_length" DECIMAL,
  "round_number" INTEGER,
  "kill_count" INTEGER,
  "headshots" INTEGER,
  "weapons" TEXT,
  "map_name" TEXT,

  -- Raw metadata from Allstar
  "metadata" JSONB,

  -- Timestamps
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY ("id"),

  -- Foreign keys
  CONSTRAINT "match_clips_match_id_fkey"
    FOREIGN KEY ("match_id")
    REFERENCES "public"."matches"("id")
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT "match_clips_match_map_id_fkey"
    FOREIGN KEY ("match_map_id")
    REFERENCES "public"."match_maps"("id")
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  -- Unique constraint on allstar_request_id
  CONSTRAINT "match_clips_allstar_request_id_key"
    UNIQUE ("allstar_request_id")
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "match_clips_match_id_idx" ON "public"."match_clips" ("match_id");
CREATE INDEX IF NOT EXISTS "match_clips_match_map_id_idx" ON "public"."match_clips" ("match_map_id");
CREATE INDEX IF NOT EXISTS "match_clips_steam_id_idx" ON "public"."match_clips" ("steam_id");
CREATE INDEX IF NOT EXISTS "match_clips_status_idx" ON "public"."match_clips" ("status");
CREATE INDEX IF NOT EXISTS "match_clips_clip_type_idx" ON "public"."match_clips" ("clip_type");
CREATE INDEX IF NOT EXISTS "match_clips_allstar_clip_id_idx" ON "public"."match_clips" ("allstar_clip_id");

-- Create trigger for updated_at
DROP TRIGGER IF EXISTS "set_public_match_clips_updated_at" ON "public"."match_clips";

CREATE TRIGGER "set_public_match_clips_updated_at"
BEFORE UPDATE ON "public"."match_clips"
FOR EACH ROW
EXECUTE PROCEDURE "public"."set_current_timestamp_updated_at"();

COMMENT ON TRIGGER "set_public_match_clips_updated_at" ON "public"."match_clips"
IS 'trigger to set value of column "updated_at" to current timestamp on row update';

-- Add comments
COMMENT ON TABLE "public"."match_clips" IS 'Stores video clips generated by Allstar API for match highlights';
COMMENT ON COLUMN "public"."match_clips"."clip_type" IS 'Type of clip: potg (Play of the Game), bp (Best Play), pmh (Player Match Highlights)';
COMMENT ON COLUMN "public"."match_clips"."status" IS 'Processing status: pending, processing, processed, error';
