export enum ButtonActions {
  VetoPick = "v",
  MapStatus = "s",
  MatchStatus = "ms",
  VoteCaptain = "vc",
  ReadyCheck = "rc",
  ConfirmSteamId = "confirm_steamid",
  CancelSteamId = "cancel_steamid",
  OpenRegisterSteamIdModal = "open_register_steamid",
  PickPlayer = "pp",
  VetoMap = "vm",
  RequestRemake = "rr",
  VoteRemake = "vr",
  AcceptMixDuel = "amd",
  DeclineMixDuel = "dmd",
  JoinDuelVoice = "jdv",
  DuelVetoBan = "dvb",
  OpenCreateTeamModal = "open_create_team",
  JoinTeam = "join_team",
  AcceptTeamMember = "accept_team_member",
  DeclineTeamMember = "decline_team_member",
  LeaveTeam = "leave_team",
}
