export enum ChatCommands {
  ScheduleComp = "competitive",
  ScheduleWingMan = "wingman",
  ScheduleDuel = "duel",
  ScheduleMix = "mix",
  ScheduleMixWingman = "mix-wingman",
  MixDuel = "mix-duel",
  LinkDiscord = "link",
  Init = "init",
  Queue = "queue",
  Ranking = "ranking",
  RankingKnife = "ranking-knife",
  RankingTaser = "ranking-taser",
  RankingMvp = "ranking-mvp",
  TestVote = "test-vote",
  TestAutoVoteCaptains = "test-auto-vote-captains",
  TestAutoReady = "test-auto-ready",
  TestAutoRemake = "test-auto-remake",
  LeaveGuild = "leave-guild",
  KickPlayer = "kick",
  RegisterSteamId = "steamid",
  CheckSteamId = "check-steamid",
  CreateTeam = "create-team",
  Migrate = "migrate",
  LfgMix = "lfg-mix",
  Warmup = "warmup",
}
