export enum ChatCommands {
  ScheduleComp = "competitive",
  ScheduleWingMan = "wingman",
  ScheduleDuel = "duel",
  ScheduleMix = "mix",
  LinkDiscord = "link",
  Init = "init",
  Queue = "queue",
  TestVote = "test-vote",
  TestAutoVoteCaptains = "test-auto-vote-captains",
  TestAutoReady = "test-auto-ready",
  TestAutoRemake = "test-auto-remake",
  LeaveGuild = "leave-guild",
  KickPlayer = "kick",
  RegisterSteamId = "steamid",
  CheckSteamId = "check-steamid",
}
